name: ci
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install -y autoconf automake libtool pkg-config flex bison libxml2-dev check libdwarf-dev valgrind
      - name: autoconf/automake
        run: |
          ./autogen.sh
      - name: check with gcc
        run: |
          ./configure CC=gcc
          make check
      - name: check with clang
        run: |
          make distclean
          ./configure CC=clang
          make check
      - name: check with valgrind
        run: |
          cd tests
          make valgrind
